### PR TITLE
Respect order of declared sources when resolving packages

### LINKED ISSUE #79: Respect order of declared sources when resolving packages
When the same version of a package exists in two source locations, the source that package is resolved from is randomly determined. E.g.; 

The source list for the `noble` distro is:

```rust
Source::new(
    "http://archive.ubuntu.com/ubuntu",
    vec!["noble", "noble-updates"],
    vec!["main", "universe"],
    include_str!("../../keys/ubuntu_24.04.asc"),
    AMD_64,
),
Source::new(
    "http://security.ubuntu.com/ubuntu",
    vec!["noble-security"],
    vec!["main", "universe"],
    include_str!("../../keys/ubuntu_24.04.asc"),
    AMD_64,
),
```

For the `curl` package, it can resolve to the following:
* `curl@8.5.0-2ubuntu10.5` from http://archive.ubuntu.com/ubuntu/pool/main/c/curl/curl_8.5.0-2ubuntu10.5_amd64.deb
* `curl@8.5.0-2ubuntu10.5` from http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_8.5.0-2ubuntu10.5_amd64.deb

Since the versions resolved are both the same, this is mostly a pain point that can cause non-deterministic tests (as can be seen [here](https://github.com/heroku/buildpacks-deb-packages/actions/runs/12183576315/job/33986993973?pr=71)). Still, respecting the implicit ordering of declared sources would eliminate this unexpected behavior.

### PR DESCRIPTION
**Pull request by colincasey**
## Summary
- Adds a `SourceOrder` type representing `(source, suite, component)` declaration indices, carried on each `RepositoryPackage`
- Replaces `Vec<RepositoryPackage>` in `PackageIndex` with `BTreeMap<PackageResolutionKey, RepositoryPackage>` so resolution ordering is structural — highest version first, first-declared source wins on ties
- Switches `update_sources` and `update_source` from `JoinSet` to `FuturesOrdered` for deterministic log output
- `build_package_index` keeps `JoinSet` since ordering is handled by the `BTreeMap`

Fixes #79

## Test plan
- [x] `SourceOrder` ordering tests (source > suite > component precedence)
- [x] `PackageResolutionKey` tests (version dominates, source order breaks ties)
- [x] Overwrite test for duplicate version + source order
- [x] All 128 unit tests pass
- [x] `cargo clippy --all-targets --locked -- --deny warnings` clean
- [x] `cargo fmt` clean

### CODE REVIEW

File: src/debian/package_index.rs [hunk 1]
```diff
@@ -1,10 +1,45 @@
...
+struct PackageResolutionKey {
+    version: debversion::Version,
+    priority: PackagePriority,
+}
+
+impl PackageResolutionKey {
+    fn new(version: &str, priority: PackagePriority) -> Self {
+        Self {
+            version: debversion::Version::from_str(version)
+                .expect("Packages should always have a valid debian version"),
```
Comment (schneems) [inline src/debian/package_index.rs:17]: Non-blocking: My preference is to have this return a Result and do the expect at the level where you know the string you're passing in is a valid version. In total isolation this interface (with no result) sort of promises "any string you give me is fine" which is not quite true.

**Review by schneems — APPROVED** [review]
Thanks. LGTM 

Commenting for context: We talked about #182 and #185. While both worked...neither was easily testable. We could have replicated a setup with some fake deb servers that we could control when they returned responses to force ordering of responses...but that would be a big lift. 

This approach tries to encode the ordering requirement via types. It's more code than #182 or #185, but I feel it better models the domain and makes the ordering logic a part of the structs directly.

File: src/debian/repository_package.rs [hunk 2]
```diff
@@ -8,6 +8,8 @@ use std::fmt::{Display, Formatter};
 #[derive(Debug, Eq, PartialEq, Clone, Hash, Serialize)]
 pub(crate) struct RepositoryPackage {
     pub(crate) repository_uri: RepositoryUri,
+    #[serde(skip)]
+    pub(crate) priority: PackagePriority,
```
Comment (schneems) [inline src/debian/repository_package.rs:12]: (optional) Noting that this changes the equality and hash semantics of the above struct. I'm unsure if it would be semantically correct for two identical packages with different priorities to be considered unequal or not.

Comment (colincasey) [reply src/debian/repository_package.rs:12]: Let's consider how you'd get this situation of "two identical packages with different source order" during execution. The only way I can see is if either the developer (while changing the source list) or a user (while adding custom sources) accidentally listed the same source twice. 

In that case, I think it's (technically) accurate to say that the index should reflect that there are two distinct entries here, one for each listed source. It's actually the source listing that's incorrect, not the index. Therefore, the `SourceOrder` should be included for equality and hash semantics. And this shouldn't affect package resolution because the first listed value would win out.

File: src/debian/package_index.rs (hunk 1 above)
Comment (colincasey) [reply src/debian/package_index.rs:17]: you're right. and this was carried over from the previous code which did this for a technical reason related to `RepositoryPackage` that i'm not sure is valid anymore. in practice it's "safe" because when we parse a debian package from the package list it **must** have a valid `debversion::Version`. only then do we add it to the index. 

let's maybe not clutter this PR up with a change here. i'll follow up in a separate PR to see if i can eliminate the parsed `debversion::Version` getting downgraded to a `String` only to then be reparsed as a `debversion::Version`.

Comment (colincasey) [reply src/debian/package_index.rs:17]: addressed in https://github.com/heroku/buildpacks-deb-packages/pull/187.

Comment (schneems) [reply src/debian/package_index.rs:17]: Think you mean #188 I see it there. we can address there. Thanks

File: src/debian/repository_package.rs (hunk 2 above)
Comment (schneems) [reply src/debian/repository_package.rs:12]: The failure mode I had in mind would be something like, if for some reason a programmer needs to find a package based on name/repository and write code that looks like it works using `==` but fails to find it because the order field is being treated as significant. Like if they wanted to reject a specific problem package (or find/warn/error on a problem package).

You've got more subject matter expertise on the mental model. So IDK if it's surprising or not. A social way to signal could be to specifically have the type have "Ordered" (or similar) in the name. 

I also think future changes would have unit tests that would (hopefully) catch it or at least raise "oh, you have to put an order in to build the unit test". So I think it's not a blocker, just a question I had and a thing to consider.

Comment (colincasey) [reply src/debian/repository_package.rs:12]: > if for some reason a programmer needs to find a package based on name/repository and write code that looks like it works using `==`

I don't think we'd want to do that. The job of the `PackageIndex` is to support those types of queries. 

Though, I think there's a subtle distinction here that's not obvious from just looking at the types - you could also view `RepositoryPackage` as actually containing a raw Debian package + source repository information. For [performance reasons](https://github.com/heroku/buildpacks-deb-packages/blob/main/src/debian/repository_package.rs#L23-L26), I ended up just parsing key fields from the raw Debian package and inlining this information into `RepositoryPackage`. If the Package was a standalone field then maybe what you're talking about would be something more like `repository_package_a.package == repository_package_b.package`?

For now though, I'm still leaning towards the source order being important to equality for it's role in `PackageIndex`.

File: src/debian/package_index.rs (hunk 1 above)
Comment (colincasey) [reply src/debian/package_index.rs:17]: too many PRs 😅
